package cc.ibooker.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cc.ibooker.greendao.entity.Friend;
import cc.ibooker.greendao.entity.User;

import cc.ibooker.greendao.FriendDao;
import cc.ibooker.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FriendDao friendDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        friendDao = new FriendDao(friendDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Friend.class, friendDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        friendDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
