package cc.ibooker.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import cc.ibooker.greendao.entity.User;

import cc.ibooker.greendao.entity.Friend;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "t_friend".
*/
public class FriendDao extends AbstractDao<Friend, Long> {

    public static final String TABLENAME = "t_friend";

    /**
     * Properties of entity Friend.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, long.class, "_id", true, "_id");
        public final static Property FId = new Property(1, long.class, "fId", false, "f_id");
        public final static Property FGname = new Property(2, String.class, "fGname", false, "f_gname");
        public final static Property FUid = new Property(3, long.class, "fUid", false, "f_uid");
    }

    private DaoSession daoSession;

    private Query<Friend> user_FriendsQuery;

    public FriendDao(DaoConfig config) {
        super(config);
    }
    
    public FriendDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"t_friend\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: _id
                "\"f_id\" INTEGER NOT NULL UNIQUE ," + // 1: fId
                "\"f_gname\" TEXT NOT NULL ," + // 2: fGname
                "\"f_uid\" INTEGER NOT NULL );"); // 3: fUid
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_t_friend__id ON \"t_friend\"" +
                " (\"_id\" ASC);");
        db.execSQL("CREATE INDEX " + constraint + "IDX_t_friend_f_id_DESC ON \"t_friend\"" +
                " (\"f_id\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"t_friend\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Friend entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.get_id());
        stmt.bindLong(2, entity.getFId());
        stmt.bindString(3, entity.getFGname());
        stmt.bindLong(4, entity.getFUid());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Friend entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.get_id());
        stmt.bindLong(2, entity.getFId());
        stmt.bindString(3, entity.getFGname());
        stmt.bindLong(4, entity.getFUid());
    }

    @Override
    protected final void attachEntity(Friend entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Friend readEntity(Cursor cursor, int offset) {
        Friend entity = new Friend( //
            cursor.getLong(offset + 0), // _id
            cursor.getLong(offset + 1), // fId
            cursor.getString(offset + 2), // fGname
            cursor.getLong(offset + 3) // fUid
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Friend entity, int offset) {
        entity.set_id(cursor.getLong(offset + 0));
        entity.setFId(cursor.getLong(offset + 1));
        entity.setFGname(cursor.getString(offset + 2));
        entity.setFUid(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Friend entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Friend entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Friend entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "friends" to-many relationship of User. */
    public List<Friend> _queryUser_Friends(long fUid) {
        synchronized (this) {
            if (user_FriendsQuery == null) {
                QueryBuilder<Friend> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FUid.eq(null));
                user_FriendsQuery = queryBuilder.build();
            }
        }
        Query<Friend> query = user_FriendsQuery.forCurrentThread();
        query.setParameter(0, fUid);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM t_friend T");
            builder.append(" LEFT JOIN t_user T0 ON T.\"f_uid\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Friend loadCurrentDeep(Cursor cursor, boolean lock) {
        Friend entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(user != null) {
            entity.setUser(user);
        }

        return entity;    
    }

    public Friend loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Friend> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Friend> list = new ArrayList<Friend>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Friend> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Friend> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
